# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.tshates.github.io
title: Tessa Shates
email: tshat003@ucr.edu
author: Tessa Shates
description: "Tessa's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/tshates
  - icon: envelope-o
    title: email
    url: mailto:tshat003@ucr.edu
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/tessa-shates-234347b9/
  - icon: file-pdf-o
    title: CV
    url: img/TessaShatesCV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/TShates

