# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.shates.github.io
title: Julia Shates
email: shates@wisc.edu
author: Julia Shates
description: "Julia's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/shates
  - icon: file-pdf-o
    title: CV
    url: img/JuliaShatesCV.pdf
  - icon: envelope-o
    title: email
    url: mailto:shates@wisc.edu
  - icon: twitter
    title: twitter
    url: https://twitter.com/jshates

